# Generated by Django 2.0.4 on 2018-06-05 03:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255, verbose_name='Apellido')),
                ('last_name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('address', models.CharField(max_length=400, verbose_name='Direcciones')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('nit', models.CharField(max_length=20, verbose_name='NIT')),
                ('dpi', models.CharField(max_length=20, verbose_name='DPI')),
                ('code_bar', models.CharField(blank=True, max_length=50, null=True, verbose_name='Códgo de barra')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'customer',
                'ordering': ['-created_at'],
                'default_related_name': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('correlative', models.IntegerField(verbose_name='Correlativo')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('payment_method', models.CharField(choices=[('H', 'Cheque'), ('C', 'Efectivo'), ('D', 'Deposito'), ('T', 'Transferir'), ('R', 'Tarjeta de crédito'), ('E', 'Tarjeta de débito')], default='C', max_length=1, verbose_name='Método de pago')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('document_number', models.TextField(blank=True, null=True, verbose_name='Número de documento')),
                ('pay_date', models.DateField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('pay_status', models.BooleanField(default=False, verbose_name='Pago')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Clientes', to='common.Customer', verbose_name='Cliente')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Usuarios', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'invoice',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='service_invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('price', models.DecimalField(decimal_places=10, max_digits=18, verbose_name='Precio')),
                ('subtotal', models.DecimalField(blank=True, decimal_places=10, max_digits=18, null=True, verbose_name='Subtotal')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Descuento')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='common.Invoice', verbose_name='Factura')),
            ],
            options={
                'verbose_name': 'Detalle de factura',
                'verbose_name_plural': 'Detalles de factura',
                'db_table': 'product_invoice',
                'default_related_name': 'productsinvoice',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=75, verbose_name='Nombre')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('price', models.DecimalField(decimal_places=10, max_digits=18, verbose_name='Precio')),
                ('description', models.CharField(blank=True, max_length=400, null=True, verbose_name='Descripción')),
                ('discount', models.DecimalField(blank=True, decimal_places=10, max_digits=18, null=True, verbose_name='Descuento')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'db_table': 'product',
                'ordering': ['-created_at'],
                'default_related_name': 'service',
            },
        ),
        migrations.AddField(
            model_name='service_invoice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products_invoice', to='common.Services', verbose_name='Servicios'),
        ),
    ]
